{
    'name': 'IN-220802-00006 - Livestock Services', 
    'owner': 'adam@thebantoo.com', 
    'creation': '2022-08-02 17:37:19.373005', 
    'modified': '2022-08-05 16:48:46.995560', 
    'modified_by': 'Administrator', 
    'parent': None, 'parentfield': None, 
    'parenttype': None, 'idx': 0, 'docstatus': 0, 
    'receiving_warehouse': 'Stores - EF', 'is_purchase': 1, 
    'data_9': '2022-08-02 17:27:29', 'edit_date': 0, 
    'supplier': 'Livestock Services', 'supplier_invoice': '-', 
    'currency': '', 'exchange_rate': 0.0, 'total_qty': 0.0, 'taxes': 0.0, 
    'grand_total': 0.0, 'remarks': None, 'naming_series': 'IN-.YY.MM.DD.-.#####. - .supplier', 
    'purchase_invoice': None, 'stock_entry_reference': None,
    'amended_from': None, 'doctype': 'Stock In', 
    'items': [{
        'name': '82fdfcf7d8', 'owner': 'Administrator', 
        'creation': '2022-08-02 17:37:19.373005', 'modified': 
        '2022-08-05 16:48:46.995560', 'modified_by': 'Administrator', 
        'parent': 'IN-220802-00006 - Livestock Services', 'parentfield': 'items', 
        'parenttype': 'Stock In', 'idx': 1, 'docstatus': 0, 'item': 'UF50', 
        'item_group': 'Fertilizer', 'item_name': 'Urea Fertilizer', 
        'batch': '-', 'qty': 0.0, 'warehouse_balance': 10.0, 'company_balance': 20.0, 
        'unit': 'Box', 'default_units': 'Nos', 'price': 0.0, 'line_value': 0.0, 
        'doctype': 'Stock In Items', '__unsaved': 1}], 
    '__unsaved': 1
    }

{
    'name': None, 'owner': None, 'creation': None, 'modified': None, 'modified_by': None, 
    'parent': None, 'parentfield': None, 'parenttype': None, 'idx': 0, 
    'docstatus': 0, 'title': None, 'naming_series': None, 'supplier': None, 'supplier_name': None, 
    'tax_id': None, 'due_date': None, 'tax_withholding_category': None, 
    'company': None, 'posting_date': None, 'posting_time': None, 'set_posting_time': 0, 
    'is_paid': 0, 'is_return': 0, 'apply_tds': 0, 'amended_from': None, 'cost_center': None, 
    'project': None, 'bill_no': None, 'bill_date': None, 'return_against': None, 'supplier_address': None, 
    'address_display': None, 'contact_person': None, 'contact_display': None, 'contact_mobile': None, 
    'contact_email': None, 'shipping_address': None, 'shipping_address_display': None, 
    'billing_address': None, 'billing_address_display': None, 'currency': None, 'conversion_rate': 0.0, 
    'buying_price_list': None, 'price_list_currency': None, 'plc_conversion_rate': 0.0, 
    'ignore_pricing_rule': 0, 'set_warehouse': None, 'rejected_warehouse': None, 'set_from_warehouse': None, 
    'supplier_warehouse': None, 'is_subcontracted': None, 'update_stock': 0, 'scan_barcode': None, 
    'total_qty': 0.0, 'base_total': 0.0, 'base_net_total': 0.0, 'total_net_weight': 0.0, 'total': 0.0, 
    'net_total': 0.0, 'tax_category': None, 'shipping_rule': None, 'taxes_and_charges': None, 
    'other_charges_calculation': None, 'base_taxes_and_charges_added': 0.0, 
    'base_taxes_and_charges_deducted': 0.0, 'base_total_taxes_and_charges': 0.0, 
    'taxes_and_charges_added': 0.0,
    'taxes_and_charges_deducted': 0.0, 'total_taxes_and_charges': 0.0, 
    'apply_discount_on': None, 'base_discount_amount': 0.0, 'additional_discount_account': None, 
    'additional_discount_percentage': 0.0, 'discount_amount': 0.0, 'base_grand_total': 0.0, 
    'base_rounding_adjustment': 0.0, 'base_rounded_total': 0.0, 'base_in_words': None, 
    'grand_total': 0.0, 'rounding_adjustment': 0.0, 'rounded_total': 0.0, 'in_words': None, 
    'total_advance': 0.0, 'outstanding_amount': 0.0, 'disable_rounded_total': 0, 
    'mode_of_payment': None, 'cash_bank_account': None, 'clearance_date': None, 
    'paid_amount': 0.0, 'base_paid_amount': 0.0, 'write_off_amount': 0.0, 
    'base_write_off_amount': 0.0, 'write_off_account': None, 'write_off_cost_center': None, 
    'allocate_advances_automatically': 0, 'payment_terms_template': None, 
    'ignore_default_payment_terms_template': 0, 'tc_name': None, 'terms': None, 
    'letter_head': None, 'select_print_heading': None, 'group_same_items': 0, 
    'language': None, 'on_hold': 0, 'release_date': None, 'hold_comment': None, 
    'status': None, 'inter_company_invoice_reference': None, 'represents_company': None, 
    'is_internal_supplier': 0, 'credit_to': None, 'party_account_currency': None, 'is_opening': None, 
    'against_expense_account': None, 'unrealized_profit_loss_account': None, 'remarks': None, 
    'from_date': None, 'to_date': None, 'auto_repeat': None, 'per_received': 0.0, 
    'doctype': 'Purchase Invoice', 
    'items': [], 
    'pricing_rules': [], 'supplied_items': [], 'taxes': [], 'advances': [], 
    'advance_tax': [], 'payment_schedule': []
}
